name: PHP CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: PHP Security Checker
      uses: StephaneBour/actions-php-security-checker@1.1

    - name: Setup project
      run: make setup

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      uses: paambaati/codeclimate-action@v2.6.0
      # Add Code Climate secret key
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make test-coverage
        coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
        debug: true
